#!/bin/sh
#
# GEISA conformance test application launching script.
# Copyright (C) 2026 Southern California Edison
#
# GEISA Conformance is free software, distributed under the Apache License
# version 2.0. See LICENSE for details.

ldconfig
/etc/cukinia/cukinia -v
