# Copyright (C) 2025 Southern California Edison

logging suite "GEISA API - Connection to MQTT broker"
cukinia_log "$(_colorize blue "--- GEISA API - Connection to MQTT broker ---")"

test_id "GEISA-API-CONN-01" \
as "Checking connection to MQTT broker" cukinia_cmd gapi_connection
