# Copyright (C) 2025 Southern California Edison

logging suite "GEISA API - Test discovery messages"
cukinia_log "$(_colorize blue "--- GEISA API - Test discovery messages ---")"

test_id "GEISA-API-DISC-01" \
as "Checking discovery status" cukinia_cmd gapi_discovery status

test_id "GEISA-API-DISC-02" \
as "Checking discovery geisa messages" cukinia_cmd gapi_discovery geisa

test_id "GEISA-API-DISC-03" \
as "Checking discovery device messages" cukinia_cmd gapi_discovery device

test_id "GEISA-API-DISC-04" \
as "Checking discovery operator messages" cukinia_cmd gapi_discovery operator

test_id "GEISA-API-DISC-05" \
as "Checking discovery metrology messages" cukinia_cmd gapi_discovery metrology

test_id "GEISA-API-DISC-06" \
as "Checking discovery sensor messages" cukinia_cmd gapi_discovery sensor

test_id "GEISA-API-DISC-07" \
as "Checking discovery network messages" cukinia_cmd gapi_discovery network

test_id "GEISA-API-DISC-08" \
as "Checking discovery waveform messages" cukinia_cmd gapi_discovery waveform
