# Copyright (C) 2026 Southern California Edison

logging suite "GEISA API - Test instantaneous messages"
cukinia_log "$(_colorize blue "--- GEISA API - Test instantaneous messages ---")"

test_id "GEISA-API-INST-01" \
as "Checking instantaneous messages" cukinia_cmd gapi_instantaneous
