# Copyright (C) 2026 Southern California Edison

logging suite "GEISA API - Test sensor messages"
cukinia_log "$(_colorize blue "--- GEISA API - Test sensor messages ---")"

test_id "GEISA-API-SENSOR-01" \
as "Checking request all readable sensors" cukinia_cmd gapi_sensor request_each_sensor

test_id "GEISA-API-SENSOR-02" \
as "Checking request not present sensor" cukinia_cmd gapi_sensor request_not_present_sensor_test
