# Copyright (C) 2025 Southern California Edison

if [[ -z "${GEE_TESTS}" || " ${GEE_TESTS} " == *" runtime_os_consumption_tests "* ]]; then
	logging suite "runtime_os_consumption_tests"
	cukinia_log "$(_colorize blue "--- Runtime OS consumption tests ---")"

	get_memory_usage()
	{
	    local ram_used_kb=$(free | awk '/^Mem:/{print $3}')
	    echo $((ram_used_kb / 1024))
	}

	RAM_CONSUMED_ON_IDLE=$(get_memory_usage)

	test_id "GEISA-EE-RUNTIME-OS-01" \
	as "OS consume less than ${MAXIMUM_RAM_CONSUMPTION_MB}MB of RAM (RAM used: ${RAM_CONSUMED_ON_IDLE}MB)" \
	cukinia_cmd awk "BEGIN { exit !($RAM_CONSUMED_ON_IDLE < $MAXIMUM_RAM_CONSUMPTION_MB) }"

	. $GEISA_EE_TESTS_DIR/tests.d/get_root_device_size.sh

	get_os_size_percent()
	{
	    local used_space=$(df / | tail -1 | awk '{print $3}')
	    local os_size_percent=$(awk "BEGIN {print ($used_space / $DEVICE_SIZE) * 100}" | awk '{printf "%f\n", $1}')
	    echo $os_size_percent
	}

	OS_SIZE_PERCENT=$(get_os_size_percent)
	test_id "GEISA-EE-RUNTIME-OS-02" \
	as "OS size is taking less than ${MAXIMUM_OS_SIZE_PERCENT}% of the available space (OS percentage size: ${OS_SIZE_PERCENT}%)" \
	cukinia_cmd awk "BEGIN { exit !($OS_SIZE_PERCENT < $MAXIMUM_OS_SIZE_PERCENT) }"
fi
